<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/12%20-%20Numpy%20Maths%20et%20Statistiques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 12/30 Numpy : Mathématiques

In [0]:
import numpy as np

## 1. Méthodes de bases (les plus utiles) de la classe ndarray

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A.sum()) # effectue la somme de tous les éléments du tableau
print(A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print(A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print(A.cumsum(axis=0)) # effectue la somme cumulée
 
print(A.prod()) # effectue le produit
print(A.cumprod()) # effectue le produit cumulé
 
print(A.min()) # trouve le minimum du tableau
print(A.max()) # trouve le maximum du tableau
 
print(A.mean()) # calcule la moyenne
print(A.std()) # calcule l'ecart type,
print(A.var()) # calcule la variance

21
[5 7 9]
[ 6 15]
[[1 2 3]
 [5 7 9]]
720
[  1   2   6  24 120 720]
1
6
3.5
1.707825127659933
2.9166666666666665


Une méthode tres importante : la méthode **argsort()**

In [19]:
A = np.random.randint(0, 10, [5, 5]) # tableau aléatoire
print(A)

[[4 2 6 2 4]
 [7 7 4 0 1]
 [6 6 6 3 3]
 [2 0 7 7 3]
 [5 7 4 9 7]]


In [20]:
print(A.argsort()) # retourne les index pour trier chaque ligne du tableau 

[[1 3 0 4 2]
 [3 4 2 0 1]
 [3 4 0 1 2]
 [1 0 4 2 3]
 [2 0 1 4 3]]


In [21]:
print(A[:,0].argsort()) # retourne les index pour trier la colonne 0 de A

[3 0 4 2 1]


In [22]:
A = A[A[:,0].argsort(), :] # trie les colonnes du tableau selon la colonne 0.
A

array([[2, 0, 7, 7, 3],
       [4, 2, 6, 2, 4],
       [5, 7, 4, 9, 7],
       [6, 6, 6, 3, 3],
       [7, 7, 4, 0, 1]])

## 2. Numpy Statistics
Correlation de Pearson :

In [23]:
B = np.random.randn(3, 3) # nombres aléatoires 3x3
 
# retourne la matrice de corrélation de B
print(np.corrcoef(B))

[[ 1.         -0.63427277  0.99937797]
 [-0.63427277  1.         -0.66114251]
 [ 0.99937797 -0.66114251  1.        ]]


In [24]:
# retourne la matrice de corrélation entre les lignes 0 et 1 de B
print(np.corrcoef(B[:,0], B[:, 1]))

[[1.         0.81847981]
 [0.81847981 1.        ]]


np.unique() :

In [27]:
np.random.seed(0)
A = np.random.randint(0, 10, [5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [28]:
np.unique(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
values, counts = np.unique(A, return_counts=True)

for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


Calculs statistiques en présence de données manquates (NaN)

In [36]:
A = np.random.randn(5, 5)
A[0, 2] = np.nan # insere un NaN dans la matrice A
 
print('ratio NaN/zise:', (np.isnan(A).sum()/A.size)) # calcule la proportion de NaN dans A
 
print('moyenne sans NaN:', np.nanmean(A)) # calcule la moyenne de A en ignorant les NaN

ratio NaN/zise: 0.04
moyenne sans NaN: 0.1832816316588837


## 3. Algebre Linéaire

In [38]:
A = np.ones((2,3))
B = np.ones((3,3))

print(A.T) # transposé de la matrice A (c'est un attribut de ndarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
print(A.dot(B)) # produit matriciel A.B

[[3. 3. 3.]
 [3. 3. 3.]]


In [45]:
A = np.random.randint(0, 10, [3, 3])
 
print('det=', np.linalg.det(A)) # calcule le determinant de A
print('inv A:\n', np.linalg.inv(A)) # calcul l'inverse de A

det= 61.00000000000001
inv A:
 [[ 0.08196721  0.63934426 -0.60655738]
 [-0.13114754 -0.62295082  0.7704918 ]
 [ 0.21311475  0.26229508 -0.37704918]]


In [44]:
val, vec = np.linalg.eig(A)
print('valeur propre:\n', val) # valeur propre
print('vecteur propre:\n', vec) # vecteur propre

valeur propre:
 [ 8.91371956 -0.86320273  1.94948316]
vecteur propre:
 [[-0.27183844 -0.6838339   0.39494311]
 [-0.4097407  -0.15279739 -0.73291062]
 [-0.87075623  0.71345929  0.55395123]]


## 4. Exercice et Solution

Standardisez la matrice suivante, c'est a dire effectuez le calcul suivant :
$A = \frac{A - mean(A_{colonne})}{std(A_{colonne})}$

In [46]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [47]:
# SOLUTION
D = (A - A.mean(axis=0)) / A.std(axis=0)
D

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [49]:
print(D.mean(axis=0)) # les moyennes sont toutes = 0
print(D.std(axis=0)) # les std sont tous = 1 

[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
[1. 1. 1. 1. 1.]
